library/event/urls.py
# urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('<int:year>/<int:month>/', views.get_month, name='calendar'),
    path('delete/<int:event_id>/', views.delete_event, name='delete_event'),
    path('modify/<int:year>/<int:month>/<int:day>/', views.day_events_form, name='day_events_form'),
    path('<int:year>/<int:month>/<int:day>/', views.day_events, name='day_events'),
    path('export_events/', views.export_events_to_ics, name='export_events'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('composition/', include('composition.urls')),
    path('repertoir', include('repertoir.urls')),
    path('news', include('news.urls')),
    path('folder/', include('folder.urls')),
    path('event/', include('event.urls')),
    path('', include('content.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = 'content.views.custom_permission_denied_view'

library/news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.listNews, name='listNews'),
    path('edit/<int:id>/', views.editNews, name='editNews'),
    path('create', views.editNews, name='createNews'),
    path('details/<int:id>/', views.detailsNews, name='detailsNews'),
    path('delete/<int:id>/', views.deleteNews, name='deleteNews'),   
    path('uploadFile/<int:id>/', views.uploadFiles, name='uploadFilesNews'),
    path('deleteFile/<int:id>/', views.deleteNewsFile, name='deleteFileNews'),
    path('setMainPicture/<int:news_file_id>/', views.set_main_image_view, name='set_main_image'),
    path('toggleActual/<int:id>/', views.checkAsActual, name='toggleActualNews'),
    path('show/<int:id>/', views.showPost, name='showPost'),
]

library/event/models.py
from datetime import date
from django.db import models

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    colour = models.CharField('colour', max_length=25, null=True, blank=True)
    date_event = models.DateField(default=date.today)  # Только дата
    start_time = models.TimeField()  # Время начала события
    end_time = models.TimeField()    # Время окончания события

    def __str__(self):
        return self.title

library/event/forms.py
# forms.py

from django import forms
from .models import Event
from django.forms import ModelForm, TextInput, TimeInput

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'start_time', 'end_time', 'colour']

        labels = {
            'title': 'Nazwa',
            'description': 'Opis',
            'start_time' : 'Czas rozpoczęcia',
            'end_time' : 'Czas końcowy',
            'colour': 'Kolor',
        }
        
        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nazwa wydarzenia'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Opis',
                'style' : 'height: 100px;'
            }),
            'colour': TextInput(attrs={
                'type' : 'color',
                'class': 'form-control form-control-color',
                'placeholder': 'Kolor (w kalendarzu)',
                'id': 'clr'
            }),
            'start_time': TimeInput(attrs={
                'type': 'time',
                'class': 'form-control w-25',
                'placeholder': 'HH:MM',
            }),
            'end_time': TimeInput(attrs={
                'type': 'time',
                'class': 'form-control w-25',
                'placeholder': 'HH:MM',
            }),

        }

library/event/views.py
# views.py
import calendar
from datetime import datetime, date, timedelta
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from .models import Event
from calendar import monthrange
from django.utils import timezone
from .forms import EventForm
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponse
from datetime import datetime

# views.py

def get_month(request, year, month):
    first_day_of_month = date(year, month, 1)
    _, days_in_month = calendar.monthrange(year, month)
    start_day = first_day_of_month.weekday()  # 0: Monday, 6: Sunday

    days = []
    for day in range(1, days_in_month + 1):
        current_date = date(year, month, day)
        events = Event.objects.filter(date_event=current_date).order_by('start_time')
        days.append({
            'day': day,
            'date': current_date,
            'events': events
        })

    today = timezone.localdate()

    days_of_week = ["Pn", "Wt", "Śr", "Cz", "Pt", "So", "N"]

    context = {
        'days_in_month': days,
        'empty_days': range(start_day),
        'prev_month': first_day_of_month.replace(day=1) - timezone.timedelta(days=1),
        'next_month': first_day_of_month.replace(day=days_in_month) + timezone.timedelta(days=1),
        'days_of_week': days_of_week,
        'current_year': year,
        'current_month': month,
        'current_month_object' : first_day_of_month,
        'today' : today
    }
    return render(request, 'event/calendar.html', context)

@permission_required('event.deleve_event', raise_exception=True)
def delete_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.delete()
    messages.success(request, f'Wydarzenie pomyślnie usunięte.')
    return redirect('calendar', year=event.date_event.year, month=event.date_event.month)

def calendar_view(request):
    events = Event.objects.all().order_by('start_time')
    return render(request, 'calendar.html', {'events': events})

@permission_required('event.change_event', raise_exception=True)
def day_events_form(request, year, month, day):
    selected_date = timezone.datetime(year, month, day).date()
    events = Event.objects.filter(date_event=selected_date).order_by('start_time')

    unique_colours = (Event.objects
                      .values('colour')
                      .distinct()
                      .order_by('-date_event')[:20])

    savedColors = []
    for color in unique_colours:
        if color not in savedColors:
            savedColors.append(color)

    event = None  # Переменная для редактируемого события

    if request.method == 'POST':
        # Удаление события
        if 'delete_event' in request.POST:
            event_id = request.POST.get('event_id')
            event = get_object_or_404(Event, id=event_id)
            event.delete()
            messages.success(request, f'Wydarzenie pomyślnie usunięte.')
            return redirect('calendar', year=year, month=month)

        # Проверяем, редактируем или создаём
        event_id = request.POST.get('event_id')
        if event_id:
            # Редактирование события
            event = get_object_or_404(Event, id=event_id)
            form = EventForm(request.POST, instance=event)
        else:
            # Создание нового события
            form = EventForm(request.POST)

        if form.is_valid():
            new_event = form.save(commit=False)
            new_event.date_event = selected_date

            # Проверяем, отмечен ли чекбокс 'cycle'
            if 'cycle' in request.POST and request.POST.get('cycleDate'):
                cycle_date_str = request.POST.get('cycleDate')
                cycle_end_date = timezone.datetime.strptime(cycle_date_str, '%Y-%m-%d').date()

                current_date = selected_date
                while current_date <= cycle_end_date:
                    new_event.pk = None
                    new_event.date_event = current_date
                    new_event.save()
                    current_date += timedelta(days=7)

                messages.success(request, f'Dodano cykliczne wydarzenie każdy tydzień do {cycle_end_date}.')
            else:
                new_event.save()
                if event_id:
                    messages.success(request, f'Wydarzenie zostało zaktualizowane.')
                else:
                    messages.success(request, f'Dodano nowe wydarzenie.')
                    
                return redirect('calendar', year=year, month=month)
    else:
        # Загружаем событие для редактирования, если оно передано через GET
        event_id = request.GET.get('event_id')
        if event_id:
            event = get_object_or_404(Event, id=event_id)
            form = EventForm(instance=event)
        else:
            form = EventForm()

    context = {
        'date': selected_date,
        'events': events,
        'form': form,
        'colors': savedColors,
        'event': event  # Передаём объект события в контекст
    }
    return render(request, 'event/day_events_form.html', context)


def export_events_to_ics(request):
    events = Event.objects.all()
    
    # Создание содержимого файла iCalendar
    ics_content = "BEGIN:VCALENDAR\n"
    ics_content += "VERSION:2.0\n"
    ics_content += "CALSCALE:GREGORIAN\n"

    for event in events:
        ics_content += "BEGIN:VEVENT\n"
        ics_content += f"SUMMARY:{event.title}\n"
        ics_content += f"DESCRIPTION:{event.description}\n"
        ics_content += f"DTSTART;TZID=Europe/Warsaw:{event.date_event.strftime('%Y%m%d')}T{event.start_time.strftime('%H%M%S')}\n"
        ics_content += f"DTEND;TZID=Europe/Warsaw:{event.date_event.strftime('%Y%m%d')}T{event.end_time.strftime('%H%M%S')}\n"
        ics_content += "END:VEVENT\n"

    ics_content += "END:VCALENDAR\n"

    # Создание HTTP-ответа с содержимым файла iCalendar
    response = HttpResponse(ics_content, content_type='text/calendar')
    response['Content-Disposition'] = 'attachment; filename="events.ics"'
    return response

def day_events(request, year, month, day):
    selected_date = timezone.datetime(year, month, day).date()
    events = Event.objects.filter(date_event=selected_date).order_by('start_time')

    context = {
        'date': selected_date,
        'selected_day':day,
        'selected_month': month,
        'selected_year': year,
        'events': events
    }

    return render(request, 'event/day_events.html', context)

library/event/templates/event/calendar.html
{% extends 'content/template.html' %}

{% block body %}


<style>
    .calendar {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        gap: 1px;
        background-color: #ddd;
    }
    .day {
        background-color: #fff;
        padding: 10px;
        min-height: 100px;
        border: 1px solid #ddd;
        position: relative;
    }
    .day:hover {
        background-color: #f0f0f0;
        cursor: pointer;
    }
    .day-number {
        position: absolute;
        top: 5px;
        right: 5px;
        font-weight: bold;
    }
    .event {
        margin-top: 10px;
        padding: 5px;
        border-radius: 3px;
        font-size: 12px;
    }
    .header {
        text-align: center;
        margin-bottom: 20px;
    }
    .nav {
        display: flex;
        justify-content: space-between;
        margin-bottom: 10px;
    }
    .today {
        border: 2px solid red;
    }
</style>

<div class="header">
    <h1 class="m-3">Kalendarz</h1>
    <div class="nav">
        <a href="{% url 'calendar' prev_month.year prev_month.month %}">← Poprzedni miesiąc</a>
        <h5>{{ current_month_object|date:"F Y" }}</h5>
        <a href="{% url 'calendar' next_month.year next_month.month %}">Kolejny miesiąc →</a>
    </div>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-primary mb-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Export Kalendarza
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Export Kalendarza</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
        <p>Aby zaimportować plik CSV do Kalendarza Google:
            <ul>
                <li>
                    Otwórz Kalendarz Google.
                </li>
                <li>
                    Kliknij przycisk "+" obok "Inne kalendarze".
                </li>
                <li>
                    Wybierz "Importuj".
                </li>
                <li>
                    Wybierz plik events.csv, który pobrałeś.
                </li>
                <li>
                    Wybierz kalendarz, do którego chcesz zaimportować wydarzenia.
                </li>
                <li>
                    Kliknij przycisk "Importuj".
                </li>
            </ul>
            Teraz możesz łatwo eksportować wydarzenia ze strony Chóru w formacie iCalendar lub CSV i importować je do Kalendarza Google!
           </p>
        </div>
        <div class="modal-footer">

        <a href="{% url 'export_events' %}" class="btn btn-outline-success">Pobierz plik</a>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
        </div>
    </div>
    </div>
</div>

<div class="calendar">
    {% for day in days_of_week %}
        <div class="day-header p-2"><strong>{{ day }}</strong></div>
    {% endfor %}

    {% for _ in empty_days %}
        <div class="day"></div>
    {% endfor %}

    {% for day in days_in_month %}
        <div class="day {% if day.date == today %}today{% endif %}" data-bs-toggle="modal" data-bs-target="#dayDetails{{ day.day }}">
            {{ day.day }}
            {% for event in day.events %}
                <div class="event" style="background-color: {{ event.colour }};">
                    <div class="title">
                        {{ event.title }}
                    </div> 
                </div>
            {% endfor %}
        </div>
        <div class="modal fade" id="dayDetails{{ day.day }}" tabindex="-1" aria-labelledby="ModalLabel{{ day.day }}" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="ModalLabel{{ day.day }}">Wydarzenia {{ day.date }}</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body p-2">
                    {% for event in day.events %}
                    <div class="event" style="background-color: {{ event.colour }};">
                        <div class="title" style="padding-top: 10px; padding-left: 10px;">
                            <h5>{{ event.title }}</h5>
                        </div> 
                    </div>
                    <div class="desc p-2">
                        {{ event.description }}
                    </div>
                    <div class="desc p-2">
                        Czas: <strong>{{ event.start_time }} - {{ event.end_time }}</strong>
                    </div>
                    <hr>
                    {% empty %}
                    <div class="p-2">
                        <p>Nie znaleziono Wydarzeń</p>
                    </div>
                    
                    {% endfor %}
                    
                </div>
                <div class="modal-footer">
                    {% if perms.event.add_event %}
                  <a href="{% url 'day_events' current_year current_month day.date.day %}" class="btn btn-outline-primary">Edycja</a>
                    {% endif %}
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Zamknij</button>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}
</div>

<div id="event-modal" style="display:none;">
    
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        function getTextColor(backgroundColor) {
            let r = parseInt(backgroundColor.substring(1, 3), 16);
            let g = parseInt(backgroundColor.substring(3, 5), 16);
            let b = parseInt(backgroundColor.substring(5, 7), 16);

            let brightness = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;

            return brightness > 0.5 ? '#000000' : '#FFFFFF';
        }

        var cards = document.querySelectorAll('.event');
        cards.forEach(function (card) {
            let backgroundColor = getComputedStyle(card).backgroundColor;
            let hexColor = rgbToHex(backgroundColor);
            card.style.color = getTextColor(hexColor);
        });

        function rgbToHex(rgb) {
            let rgbArray = rgb.match(/\d+/g);
            return `#${(1 << 24 | (parseInt(rgbArray[0]) << 16) | (parseInt(rgbArray[1]) << 8) | parseInt(rgbArray[2])).toString(16).slice(1).toUpperCase()}`;
        }
    });
</script>
    
{% endblock %}

library/event/templates/event/day_events.html
{% extends 'content/template.html' %}

{% block body %}

<style>
    .colorBox{
        cursor: pointer;
        width: 48px;
        height: 40px;
    }
</style>

<h2 class="text-center m-3">Wydarzenia {{ date|date:"d F Y" }}</h2>



<div class="container">
    <a href="{% url 'day_events_form' selected_year selected_month selected_day %}" class="btn btn-outline-success mx-1 mb-2">Dodaj wydarzenie</a>
    {% for event in events %}

    <div class="card mb-3 mx-1">
        <div class="row g-0 h-100">
            <div class="card-img-top w-100 p-2" style="background-color: {{ event.colour }};">
                <h4>{{ event.title }}</h5>      
            </div>
              <div class="card-body">
                <p class="card-text text-truncate">{{ event.description }}</p>
                <strong>({{ event.start_time|date:"H:i" }} - {{ event.end_time|date:"H:i" }})</strong><br>
                <div class="pt-1">
                    <input type="hidden" name="event_id" value="{{ event.id }}">
                    {% if perms.event.add_event %}
                        <a href="{% url 'day_events_form' selected_year selected_month selected_day %}?event_id={{ event.id }}" class="btn btn-outline-primary">Edycja</a>
                    {% endif %}

                    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteEvent{{ event.id }}">
                        Usuń
                    </button>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="deleteEvent{{ event.id }}" tabindex="-1" aria-labelledby="deleteEvent{{ event.id }}Label" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="deleteEvent{{ event.id }}Label">Potwierdź akcję</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body"> 
                                    Napewno chcesz usunąć to wydarzenie ?
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-outline-danger w-25" href="{% url 'delete_event' event_id=event.id %}">Tak</a>
                                    <button type="button" class="btn btn-secondary w-25" data-bs-dismiss="modal">Nie</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% empty %}
    <p class="card-text"><small class="text-body-secondary">Nie ma nic zaplanowanego na ten dzień</small></p>
{% endfor %}
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
        function getTextColor(backgroundColor) {
            let r = parseInt(backgroundColor.substring(1, 3), 16);
            let g = parseInt(backgroundColor.substring(3, 5), 16);
            let b = parseInt(backgroundColor.substring(5, 7), 16);

            let brightness = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;

            return brightness > 0.5 ? '#000000' : '#FFFFFF';
        }

        var cards = document.querySelectorAll('.card-img-top');
        cards.forEach(function (card) {
            let backgroundColor = getComputedStyle(card).backgroundColor;
            let hexColor = rgbToHex(backgroundColor);
            card.style.color = getTextColor(hexColor);
        });

        var modals = document.querySelectorAll('.modal-header');
        modals.forEach(function (modal) {
            let backgroundColor = getComputedStyle(modal).backgroundColor;
            let hexColor = rgbToHex(backgroundColor);
            modal.querySelector('.toPrint').style.color = getTextColor(hexColor);
        });

        function rgbToHex(rgb) {
            let rgbArray = rgb.match(/\d+/g);
            return `#${(1 << 24 | (parseInt(rgbArray[0]) << 16) | (parseInt(rgbArray[1]) << 8) | parseInt(rgbArray[2])).toString(16).slice(1).toUpperCase()}`;
        }
    });
</script>
{% endblock %}

library/event/templates/event/day_events_form.html
{% extends 'content/template.html' %}

{% block body %}

<style>
    .colorBox{
        cursor: pointer;
        width: 48px;
        height: 40px;
    }
</style>

<h2 class="text-center m-3">Nowe wydarzenie {{ date|date:"d F Y" }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    {% if event %}
        <input type="hidden" name="event_id" value="{{ event.id }}">
    {% endif %}

    {% if colors %}
    <div class="row">
        <label>Ostatnio użyte kolory:</label>
        {% for color in colors %}
        <div class="colorBox m-3" style="background-color: {{ color.colour }};" onclick="setColor(this)"></div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="form-check mt-3 mb-3">
        <input class="form-check-input" type="checkbox" value="" name="cycle" id="cycle">
        <label class="form-check-label" for="cycle">
            Wydarzenie cykliczne w ten dzień tygodnia
        </label>
    </div>

    <div class="form-check mt-3 mb-3">
        <label class="form-check-label" for="cycleDate">
            Data końcowa
        </label>
        <input class="form-control mt-2 w-25" type="date" value="" name="cycleDate" id="cycleDate">
    </div>

    <input type="submit" class="btn btn-outline-success" value="Zapisz">
</form>

<script>
    function setColor(element) {
        const formPart = document.getElementById('clr');
        const backgroundColor = window.getComputedStyle(element).backgroundColor;
        console.log("Background color:", backgroundColor);
        formPart.value = rgbToHex(backgroundColor);
    }

    function rgbToHex(rgb) {
        var rgbArray = rgb.match(/\d+/g);
        var r = parseInt(rgbArray[0]).toString(16).padStart(2, '0');
        var g = parseInt(rgbArray[1]).toString(16).padStart(2, '0');
        var b = parseInt(rgbArray[2]).toString(16).padStart(2, '0');
        return `#${r}${g}${b}`;
    }
</script>
{% endblock %}