library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('composition/', include('composition.urls')),
    path('repertoir', include('repertoir.urls')),
    path('news', include('news.urls')),
    path('folder/', include('folder.urls')),
    path('event/', include('event.urls')),
    path('', include('content.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = 'content.views.custom_permission_denied_view'

library/news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.listNews, name='listNews'),
    path('edit/<int:id>/', views.editNews, name='editNews'),
    path('create', views.editNews, name='createNews'),
    path('details/<int:id>/', views.detailsNews, name='detailsNews'),
    path('delete/<int:id>/', views.deleteNews, name='deleteNews'),   
    path('uploadFile/<int:id>/', views.uploadFiles, name='uploadFilesNews'),
    path('deleteFile/<int:id>/', views.deleteNewsFile, name='deleteFileNews'),
    path('setMainPicture/<int:news_file_id>/', views.set_main_image_view, name='set_main_image'),
    path('toggleActual/<int:id>/', views.checkAsActual, name='toggleActualNews'),
    path('show/<int:id>/', views.showPost, name='showPost'),
]

library/repertoir/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.listRepertoirs, name='listRepertoirs'),
    path('add', views.editRepertoir, name='addRepertoir'),
    path('edit/<int:pk>/', views.editRepertoir, name='editRepertoir'),
    path('delete/<int:pk>/', views.deleteRepertoir, name='deleteRepertoir'),
]

library/repertoir/models.py
from django.db import models

class Repertoir(models.Model):
    title = models.CharField('title', max_length=400)
    text = models.CharField('text', max_length=1500)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Repertoir'
        verbose_name_plural = 'Repertoirs'

library/repertoir/forms.py
from django import forms
from .models import Repertoir
from django.forms import ModelForm, TextInput

class RepertoirForm(forms.ModelForm):
    class Meta:
        model = Repertoir
        fields = ['title', 'text']

        labels = {
            'title': 'Nagłówek',
            'text': 'Tekst',
        }

        widgets = {
            'title': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nazwa'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Notatki',
                'style' : 'height: 150px;'
            }),
        }
        

library/repertoir/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Repertoir
from .forms import RepertoirForm
from django.contrib import messages

def listRepertoirs(request):
    repertoirs = Repertoir.objects.all().order_by('-id')
    return render(request, 'repertoir/list.html', {'repertoirs': repertoirs})

def editRepertoir(request, pk=None):
    if pk:
        repertoir = get_object_or_404(Repertoir, pk=pk)
        action = 'update'
    else:
        repertoir = None
        action = 'add'

    if request.method == 'POST':
        form = RepertoirForm(request.POST, instance=repertoir)
        if form.is_valid():
            new_repertoir = form.save()
            if action == 'add':
                messages.success(request, f'Repertuar {new_repertoir.title} został pomyślnie dodany do biblioteki.')
            else:
                messages.success(request, f'Repertuar {new_repertoir.title} został pomyślnie zaktualizowany.')
            
            return redirect('listRepertoirs')
        else:
            messages.error(request, 'Coś poszło nie tak')
    else:
        form = RepertoirForm(instance=repertoir)

    return render(request, 'repertoir/form.html', {'form': form})


def deleteRepertoir(request, pk):
    repertoir = get_object_or_404(Repertoir, pk=pk)
    repertoir_name = repertoir.title  # сохранить имя для уведомления

    try:
        repertoir.delete()
        messages.success(request, f'Teczka "{repertoir_name}" została pomyślnie usunięta.')
    except Exception as e:
        messages.error(request, f'Niestaty nie udało się usunąć teczki "{repertoir_name}": {str(e)}')

    return redirect('listRepertoirs')

library/repertoir/templates/repertoir/form.html
{% extends 'content/template.html' %}

{% load static %}
{% block body %}

<div class="pt-2">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'listRepertoirs' %}">Repertuar</a></li>
            <li class="breadcrumb-item active" aria-current="page">Formularz repertuaru</li>
        </ol>
    </nav>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10 col-12">
            <h2 class="mt-5 text-center">Rerertuar</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {% if error_message %}
                    <p class="text-danger text-center">{{ error_message }}</p>
                {% endif %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-success mt-2">Zapisz</button>
                </div>
            </form>
            {% if error %}
                <p class="text-danger text-center">{{ error }}</p>
            {% endif %}
        </div>
    </div>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

{% endblock %}

library/repertoir/templates/repertoir/list.html
{% extends 'content/template.html' %}

{% load static %}
{% block body %}

<div class="row justify-content-center">
    <div class="container-fluid">
        <h2 class="text-center mt-3 mb-4">Repertuar</h2>
        <div class="row justify-content-center mb-3">
            {% if perms.repertoir.add_repertoir %}
            <div class="col-6 col-md-2 mt-1 mb-1 text-center">
                <a class="btn w-75 btn-outline-success" href="{% url 'addRepertoir' %}" role="button">Nowy repertuar</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="container col-sm-10 col-md-9 col-lg-8 p-3 mb-3 h-auto">
       {% for repertoir in repertoirs %}
        <div class="card anim shadow rounded mb-3">
                <div class="card-header">
                    {{ repertoir.title }}
                </div>
                <div class="card-body">
                    {{ repertoir.text|linebreaksbr }}
                </div>
                <div class="card-footer">
                    {% if perms.repertoir.change_repertoir %}
                    <a href="{% url 'editRepertoir' pk=repertoir.id %}" class="btn btn-outline-primary">Edycja</a>
                    {% endif %}
                    {% if perms.repertoir.delete_repertoir %}
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                        Usuń
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="deleteModalLabel">Potwierdź akcję</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body"> 
                                    Napewno chcesz usunąć repertuar <b>{{ repertoir.title }}</b>?
                                </div>
                                <div class="modal-footer">
                                    <a href="{% url 'deleteRepertoir' pk=repertoir.id %}" class="btn btn-outline-danger w-25">Tak</a>
                                    <button type="button" class="btn btn-secondary w-25" data-bs-dismiss="modal">Nie</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
       {% endfor %}
    </div>
</div>

{% endblock %}