library/content/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='main'),
    path('managers', views.managers, name='managers'),
    path('news', views.news, name='news'),
    path('conductor', views.conductor, name='conductor'),
    path('viceConductor', views.viceConductor, name='viceConductor'),
    path('hoffman', views.hoffman, name='hoffman'),
    path('history', views.history, name='history'),
    path('sandbox', views.sandbox, name='sandbox'),
    path('contact', views.contact, name='contact'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('composition/', include('composition.urls')),
    path('repertoir', include('repertoir.urls')),
    path('news', include('news.urls')),
    path('folder/', include('folder.urls')),
    path('event/', include('event.urls')),
    path('', include('content.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = 'content.views.custom_permission_denied_view'

library/news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.listNews, name='listNews'),
    path('edit/<int:id>/', views.editNews, name='editNews'),
    path('create', views.editNews, name='createNews'),
    path('details/<int:id>/', views.detailsNews, name='detailsNews'),
    path('delete/<int:id>/', views.deleteNews, name='deleteNews'),   
    path('uploadFile/<int:id>/', views.uploadFiles, name='uploadFilesNews'),
    path('deleteFile/<int:id>/', views.deleteNewsFile, name='deleteFileNews'),
    path('setMainPicture/<int:news_file_id>/', views.set_main_image_view, name='set_main_image'),
    path('toggleActual/<int:id>/', views.checkAsActual, name='toggleActualNews'),
    path('show/<int:id>/', views.showPost, name='showPost'),
]

library/content/models.py
from django.db import models

# Create your models here.

library/user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    voice_type = models.CharField(max_length=10, default='guest')
    last_activity = models.DateTimeField(null=True, blank=True)
    
    #Это поле используется для определения, имеет ли пользователь доступ к админ-панели Django (/admin). 
    # Если значение is_staff установлено в True, пользователь сможет войти в админ-панель (если у него есть доступ).
    is_staff = models.BooleanField(default=False)

    # Поле Active определяет, активен ли пользователь. Если значение is_active установлено в False, 
    # пользователь не сможет войти в систему, даже если его учетные данные верны.
    is_active = models.BooleanField(default=True)    
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'surname']

    def __str__(self):
        return self.email

library/content/views.py
from django.shortcuts import render
from news.models import News
from event.models import Event
from datetime import date
import random
from django.db.models import Q, Min
from django.utils import timezone

def index(request):
    news = list(News.objects.filter(isActual=True))
    now = timezone.now()  # Текущее время
    closest_date = Event.objects.filter(
        Q(date_event__gt=now.date()) |  # Будущие события
        Q(date_event=now.date(), start_time__gte=now.time())  # Сегодняшние, начиная с текущего времени
    ).aggregate(Min('date_event'))['date_event__min']

    if closest_date:
        events = Event.objects.filter(date_event=closest_date).order_by('start_time')
    else:
        events = []
    random.shuffle(news)
    return render(request, 'content/index.html', {'news': news, 'events': events, 'date': closest_date})

def sandbox(request):
    return render(request, 'content/bubbles.html')

def managers(request):
    return render(request, 'content/managers.html')


def news(request):
    return render(request, 'content/news.html')


def contact(request):
    return render(request, 'content/contact.html')


def conductor(request):
    return render(request, 'content/conductor.html')


def viceConductor(request):
    return render(request, 'content/viceConductor.html')


def history(request):
    return render(request, 'content/history.html')


def hoffman(request):
    return render(request, 'content/hoffman.html')

def custom_permission_denied_view(request, exception):
    return render(request, 'content/403.html', status=403)

library/content/templates/content/conductor.html
{% extends 'content/template.html' %}

{% load static %}
{% block body %}

<!-- Container for the content -->
<div class="container my-5">
    <div id="choir" class="container-fluid text-center mb-5">
        <h1 class="display-4">
            Dyrygent Ks. Michał Roman Szulik
        </h1>
    </div>

    <!-- Main content area -->
    <div class="container-fluid">
        <div class="shadow-lg p-2 p-md-2 p-lg-3 p-xl-5">
            <div class="row">
                <div class="col-md-6">
                    <img src="{% static 'content/img/szulik.jpeg' %}" class="img-fluid rounded mb-3 mb-md-0" alt="Ks. Michał Roman Szulik">
                </div>
                <div class="col-md-6">
                    <p class="text-justify">
                        Ukończył PSM II stopnia w Lublinie w klasie śpiewu solowego prof. Aliny Naumowicz. Swoje umiejętności
                        śpiewacze doskonalił także u Prof. Jadwigi Gałeskiej-Trit (Poznań), Alicji Molędy-Borkowskiej (Drezno) oraz
                        prof. Gerlinde Schmid - Nafz (Überlingen). Po studiach w Wyższym Seminarium Duchownym w Siedlcach (1994)
                        studiował muzykologię na KUL, którą ukończył w roku 2001. W zakresie dyrygentury chóralnej jest uczniem ad.
                        Kazimierza Bukata, dyrygenta Chóru Filharmonii Narodowej w Warszawie. Swoje zainteresowanie dyrygenckie
                        rozwijał już w czasie studiów prowadząc między innymi Chór WSD O.O. Kapucynów w Lublinie, będąc
                        korepetytorem Chóru Archikatedry Lubelskiej oraz współpracując z Chórem i Orkiestrą Młodzieżową Cantate Deo
                        w Lublinie. Z Chórem Katedralnym w Siedlcach pracuje od jesieni 1999 r. W ciągu pięciu lat pracy w Siedlcach
                        przygotował z zespołem oprawę muzyczną do wszystkich uroczystości w katedrze a także większych uroczystości
                        o zasięgu diecezjalnym. W ciągu 6 pracy przygotował z Chórem ok. 30 koncertów w rożnych miastach Polski i
                        za granicą.
                    </p>
                    <hr class="my-4">
                    <p class="text-justify">
                        Zajmuje się pracą kompozytorską. Jest także odpowiedzialny za całokształt muzyki kościelnej w Diecezji
                        Siedleckiej a także prowadzi Diecezjalne Studium Muzyki Od 2003 roku pracuje w Zakładzie Muzyki Wydziału
                        Humanistycznego Akademii Podlaskiej. W roku 2005 uzyskał w Akademii Muzycznej w Poznaniu tytuł doktora
                        sztuki muzycznej w dyscyplinie artystycznej dyrygentura na podstawie przedstawionej rozprawy doktorskiej
                        pt."Rola słowa i tekstu w religijnej muzyce chóralnej na przykładzie wybranych utworów od renesansu do
                        współczesności. Próby wskazówek interpretacyjnych.
                    </p>
                    <hr class="my-4">
                    <p class="text-justify">
                        Większe utwory napisane przez ks. Michała Szulika:
                        <ul class="list-unstyled">
                            <li>
                                <span class='font-weight-bold'>"Te Deum laudamus"</span> - na sopran solo, chór mieszany, zespół
                                instrumentów dętych i organy (prawykonanie - styczeń 2001, 6 koncertów w diecezji siedleckiej)
                            </li>
                            <li>
                                <span class='font-weight-bold'>Mottet "Evangelio oboedientia. Eucharistia."</span> - na 3 chóry
                                mieszane, kwartet dęty i organy (prawykonanie - czerwiec 2002)
                            </li>
                            <li>
                                <span class='font-weight-bold'>"Requiem f-moll"</span> - na sopran i tenor solo, chór mieszany i
                                organy (prawykonanie - lipiec 2004, koncert w Überlingen 2005)
                            </li>
                            <li>
                                <span class='font-weight-bold'>Psalm 150</span> - na chór mieszany i organy (prawykonanie -
                                listopad 2004)
                            </li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

library/content/templates/content/contact.html
{% extends 'content/template.html' %}

{% block body %}

<div id="contact" class="container-fluid">
        <h1 class="text-center mt-5 mb-5">
            Stowarzyszenie Chór Katedralny im. ks. <br>Alfreda Hoffmana w Siedlcach
        </h1>
        <h2 class="text-center">
            ul. Kochanowskiego 11, 08-110 Siedlce
        </h2>
        <h3 class="text-center">
            chorkatedralny.siedlce@gmail.com
        </h3>
        <h3 class="text-center mb-5">
            tel. +48 506 046 646
        </h3>
        <div class="text-center">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2447.0640696455553!2d22.2714792753876!3d52.169528562119964!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471f5a53b5c42c47%3A0xc404b1b0c69c75f5!2sCathedral%20of%20the%20Immaculate%20Conception!5e0!3m2!1sru!2spl!4v1715533968867!5m2!1sru!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
</div>
{% endblock %}

library/content/templates/content/footer.html
{% load static %}
<footer class="text-center mt-5 border-top bg-light">
    <div class="container-fluid px-0">
        <div class="row justify-content-between align-items-center mx-0">
            <div class="col-md-3 mb-3 mb-3 md-0">
                <img class="m-0 p-0" src="{% static 'content/img/logo_dark_with_text.svg' %}" width="240px" alt="Chór Katedralny">
            </div>
            <div class="col-md-6 mb-md-0">
                <p>Chór Katedralny im. Ks. Alfreda Hoffmana | Siedlce 2024</p>
            </div>
            <div class="col-md-3">
                <ul class="list-inline mb-0 justify-content-end">
                    <li class="list-inline-item">
                        <a class="text-body-secondary me-3" href="https://www.instagram.com/chorkatedralny.siedlce?utm_medium=copy_link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="#000" class="bi bi-instagram" viewBox="0 0 16 16">
                                <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                            </svg>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-body-secondary" href="https://www.facebook.com/chorkatedralny.siedlce">
                            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="#000" class="bi bi-facebook" viewBox="0 0 16 16">
                                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                            </svg>
                        </a>
                    </li>
                </ul>
            </div

library/content/templates/content/image.html
{% load static %}

library/content/templates/content/index.html
{% extends 'content/template.html' %}

{% load static %}
{% block body %}

<div class="container">
    <div id="choir" class="container-fluid mb-5">
        <div class="row flex-column flex-md-row align-items-center">
            <div class="col-auto">
                <img class="m-0 p-0" src="{% static 'content/img/logo_dark.svg' %}" width="170px" alt="Chór Katedralny">
            </div>
            <div class="col text-center text-md-start pt-5">
                <h1 class="mb-0">Chór Katedralny im. ks. Alfreda Hoffmana w Siedlcach</h1>
            </div>
        </div>
    </div>
    
    
    <div class="container-fluid">
        <div class="shadow-lg p-2 p-md-2 p-lg-3 p-xl-5 mb-3">

            <div class="container mt-3">
                <h3 class="display-6"><strong>Aktualności</strong></h3>
            </div>
            
            <div id="newsCarousel" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    {% for post in news %}
                    <button type="button" data-bs-target="#newsCarousel" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %} bg-secondary" aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}"></button>
                    {% endfor %}
                </div>
            
                <div class="carousel-inner">
                    {% for post in news %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %} pb-4">
                        <div class="card mb-3 mx-1">
                            <div class="row g-0 h-100">
                                <div class="col-md-4" style="border-right: 1px solid #ccc; height: 200px;">
                                    {% for file in post.files.all %}
                                        {% if file.is_main %}
                                        <img src="{{ file.file.url }}" class="img-fluid rounded-start w-100 h-100" style="object-fit: cover;" alt="{{ file.get_file_type_display }}">
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="col-md-8 justify-content-between">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ post.title }}</h5>
                                        <p class="text-truncate">{{ post.text }}</p>
                                    </div>
                                    <div class="card-footer bg-white border-0 d-flex justify-content-between align-items-end">
                                        <a href="{% url 'showPost' id=post.id %}" class="btn btn-outline-secondary">Szczegóły</a>
                                        <p class="card-text mb-0"><small class="text-body-secondary">{{ post.date_joined }}</small></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            {% if events %}
            <div class="mb-3">
                <div class="container">
                    <h4 class="display-6">Najbliższe wydarzenia</h3>
                </div>
                <div class="container">
                    
                    <h5 class="display-8">{{ date }}</h5>
                </div>
            
                {% for event in events %}
                <div class="container">
                    <div class="p-3 rounded-2 bg-light">
                        <h4>{{ event.title }}</h4>
                        {{ event.description }}<br>
                        <strong>{{ event.start_time }} - {{ event.end_time }}</strong><br>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}
    
            <div class="container">
                <h4 class="display-6">O nas</h4>
                <div class="row">
                    <div class="col-12">
                        <p align="justify">
                            Chór Katedralny im <a href="{% url 'hoffman' %}">ks. Alfreda Hoffmana</a> jest zespołem, który wyrasta
                            z niemalże stuletniej tradycji chóralnej kościoła pod wezwaniem Niepokalanego Poczęcia
                            Najświętszej Maryi Panny w Siedlcach.
                            Głównym zadaniem Chóru Katedralnego im ks. Alfreda Hoffmana
                            w Siedlcach jest służba liturgii podczas celebracji w kościele biskupim
                            a także podczas większych uroczystości na terenie diecezji siedleckiej.<br><br><img class="mb-3" width="100%" src="{% static 'content/img/tlo.jpg' %}">
                            W repertuarze zespołu, oprócz utworów liturgicznych znajdują się także utwory koncertowe,
                            z którymi chór występował na terenie kraju a także
                            w Niemczech, Włoszech, na Węgrzech, Ukrainie i Białorusi.<br>
                            Chór ma w swoim repertuarze wiele kompozycji dyrygenta, <a href="{% url 'conductor' %}">ks. Michała Szulika</a>.
                            Istotnym aspektem działalności chóru katedralnego jest praca wychowawcza
                            i wspieranie rozwoju uzdolnionej muzycznie młodzieży.<br>
                            Od 1999 r. chór prowadzi ks. Michał Szulik, którego asystentką od 2014 r. jest <a href="{% url 'viceConductor' %}">Izabela Kiryluk</a>.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

library/content/templates/content/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">


    <title>Chór Katedralny im. Ks. Alfreda Hoffmana w Siedlcach</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <!-- Toastr -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'content/css/main.css' %}">

    <link rel="stylesheet" href="{% static 'content/css/scss.scss' %}">
</head>

<style>
    .bg-dark{
        background-color: rgb(19, 18, 18) !important;
    }
</style>

<body class="body-bg">
    <div class="overlay">
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark sticky-top">
            <div class="container main-container">
                <img class="m-0 p-0" src="{% static 'content/img/logo_light.svg' %}" width="65px" alt="Chór Katedralny">
                <a class="navbar-brand text-center" href="/">
                    Chór Katedralny
                </a>
                <button class="navbar-toggler bg-dark" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false"
                        aria-label="Przewodnik">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'listNews' %}">Aktualności</a>
                        </li>

                        {% if user.is_authenticated %}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Biblioteka
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'listComposition' %}">Utwory</a></li>
                                <li><a class="dropdown-item" href="{% url 'listFolder' %}">Teczki</a></li>
                                {% if perms.composition.change_composition %}
                                <li><a class="dropdown-item" href="{% url 'listRepertoirs' %}">Repertuar</a></li>
                                <!-- <li><a class="dropdown-item disabled" href="#">Ustawienia</a></li> -->
                                {% endif %}
                                {% if perms.user.change_user %}
                                <li><a class="dropdown-item" href="{% url 'manageUsers' %}">Użytkownicy</a></li>
                                {% endif %}
                            </ul>
                        </li>

                        {% else %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'listComposition' %}">Biblioteka</a>
                        </li>

                        {% endif %}

                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    O chórze
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'conductor' %}">Dyrygent</a></li>
                                    <li><a class="dropdown-item" href="{% url 'viceConductor' %}">II Dyrygent</a></li>
                                    <li><a class="dropdown-item" href="{% url 'hoffman' %}">Ks. A. Hoffmann</a></li>
                                    <li><a class="dropdown-item" href="{% url 'managers' %}">Zarząd Chóru</a></li>
                                    <li><a class="dropdown-item" href="{% url 'history' %}">Historia chóru</a></li>
                                </ul>
                            </li>
                        </ul>
                        <li class="nav-item">
                            {% if current_year and current_month %}
                            <a class="nav-link" href="{% url 'calendar' current_year current_month %}">Kalendarz</a>
                            {% else %}
                                <a class="nav-link" href="#">Kalendarz</a>  <!-- Ссылка или сообщение для случая, когда данные отсутствуют -->
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Kontakt</a>
                        </li>
                    </ul>

                    {% if user.is_authenticated %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                   Witaj, {{ user.name }}
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li>
                                        <form method="post" action="{% url 'logout' %}">
                                            {% csrf_token %}
                                            <button type="submit" class="dropdown-item">Wyloguj</button>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        
                    {% else %}
                        <a class="btn btn-success" href="{% url 'signIn' %}" role="button">Zaloguj</a>
                    {% endif %}
        
                </div>
            </div>
        </nav>

        <div class="container main-container align-items-center" style="min-height: 90vh; width: 100%">

            <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 11">
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="toast toast-success" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
                    {% elif message.tags == 'error' %}
                        <div class="toast toast-error" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
                    {% elif message.tags == 'warning' %}
                        <div class="toast toast-warning" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
                    {% else %}
                        <div class="toast toast-info" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true">
                    {% endif %}
                        <div class="toast-header">
                            <img class="m-0 p-0" src="{% static 'content/img/logo_dark.svg' %}" width="30px" alt="Chór Katedralny">

                            {% if message.tags == 'success' %}
                                <strong class="me-auto">Sukces!</strong>
                            {% elif message.tags == 'error' %}
                                <strong class="me-auto">Nie powiodło się..</strong>
                            {% elif message.tags == 'warning' %}
                                <strong class="me-auto">Uwaga</strong>
                            {% else %}
                                <strong class="me-auto">Uwaga</strong>
                            {% endif %}
                            <small class="text-body-secondary">{% now "Y-m-d H:i:s" %}</small>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Zamknij"></button>
                        </div>
                        <div class="toast-body">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var toastElList = [].slice.call(document.querySelectorAll('.toast'))
                    var toastList = toastElList.map(function (toastEl) {
                        return new bootstrap.Toast(toastEl)
                    })
                    toastList.forEach(toast => toast.show())
                });
            </script>

            {% block body %}
            {% endblock %}
        </div>



        {% include 'content/footer.html' %}
    </div>

    {% block extra_js %}{% endblock %}
</body>
</html>